# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, verbose_name='Brand Name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, verbose_name='Product Name')),
                ('description', models.TextField(verbose_name='Product Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('is_active', models.BooleanField(default=False)),
                ('product_type', models.CharField(blank=True, max_length=2, null=True)),
                ('is_variation', models.BooleanField(default=False)),
                ('code', models.IntegerField(default=0)),
                ('family', models.IntegerField(default=0)),
                ('is_complement', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date')),
                ('modified', models.DateTimeField(editable=False, verbose_name='Modified date')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
                ('is_visibility', models.BooleanField(default=False, verbose_name='Visible')),
                ('price', models.DecimalField(decimal_places=3, default=False, max_digits=10, verbose_name='Precio')),
                ('price_offer', models.DecimalField(blank=True, decimal_places=3, default=False, max_digits=10, null=True, verbose_name='Precio de  Oferta')),
                ('offer_day_from', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio de oferta')),
                ('offer_day_to', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin de oferta')),
                ('sku', models.IntegerField(default=0, verbose_name='SKU')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Product quantity')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, verbose_name='Tag Name')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.ProductTags', verbose_name='Product tags'),
        ),
    ]
