# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, verbose_name='Product Name')),
                ('description', models.TextField(verbose_name='Product Description')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Product quantity')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, verbose_name='Tag Name')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='api.ProductTags', verbose_name='Product tags'),
        ),
    ]
