# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.ProductTags', verbose_name='Product tags'),
        ),
    ]
