# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_productdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='sku',
            field=models.IntegerField(default=0, verbose_name='SKU'),
        ),
    ]
