# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_productdetail_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='product_id',
            new_name='product',
        ),
    ]
