# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180220_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='price_offer',
            field=models.DecimalField(blank=True, decimal_places=3, default=False, max_digits=10, null=True, verbose_name='Precio de  Oferta'),
        ),
    ]
