# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180220_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='offer_day_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio de oferta'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='offer_day_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin de oferta'),
        ),
    ]
